#pragma once

// COLORS
#define RED 1
#define GREEN 2
#define BLUE 3
#define WHITE 4

// KEYBOARD KEYS
#define SPACEBAR 32
#define ESCAPE 27

// BOUNDING BOX
#define X_MAX 100
#define X_MIN -100
#define Y_MAX 100
#define Y_MIN -100
#define Z_MAX 20
#define Z_MIN -100

// SPACESHIP
#define SPACESHIP_Y 15
#define SPACESHIP_X 30

// STARS
#define STAR_INITIAL_Z -100
#define STAR_NUMBER 80
#define STAR_SPEED 0.01

// ASTEROIDS
#define ASTEROID_INITIAL_SPEED 0.05
#define ASTEROID_SPEED_INCREMENT 0.005
#define ASTEROID_MAX_SPEED 0.2
#define ASTEROID_INITIAL_GEN_FREQUENCY 2000
#define ASTEROID_GEN_FREQUENCY_DECREMENT 100 
#define ASTEROID_MIN_GEN_FREQUENCY 800
#define ASTEROID_MAX_ASTEROIDS_PER_GEN 10

// TEXT
#define MAX_TEXT_LENGTH 20
#define TEXT_Z 0
#define TEXT_SIZE 0.005

// PSYCHEDELIC WELL
#define RANDOM_ITEM_NO 100
#define RANDOM_ITEM_MIN_SPEED -0.01
#define RANDOM_ITEM_MAX_SPEED 0.01
#define RANDOM_ITEM_MIN_ROT_SPEED -0.001
#define RANDOM_ITEM_MAX_ROT_SPEED 0.001

// ENDGAME
#define DARKEN_DECREMENT 0.008
#define DARKEN_TIMES 400

// SUN
#define SUN_POSITION_X 50
#define SUN_POSITION_Y 20
#define SUN_POSITION_Z -110

// LIGHTING
#define AMBIENT_RED 0
#define AMBIENT_GREEN 0
#define AMBIENT_BLUE 0
#define DIFFUSE_RED 0.8
#define DIFFUSE_GREEN 0.8
#define DIFFUSE_BLUE 0.8
#define SPECULAR_RED 0.8
#define SPECULAR_GREEN 0.8
#define SPECULAR_BLUE 0.8