#pragma once

// COLORS
#define RED 1
#define GREEN 2
#define BLUE 3
#define WHITE 4

// KEYBOARD KEYS
#define SPACEBAR 32
#define ESCAPE 27

// BOUNDING BOX
#define X_MAX 100
#define X_MIN -100
#define Y_MAX 100
#define Y_MIN -100
#define Z_MAX 20
#define Z_MIN -100

// SPACESHIP
#define SPACESHIP_Y 15
#define SPACESHIP_X 30

// STARS
#define STAR_INITIAL_Z -100
#define STAR_NUMBER 80
#define STAR_SPEED 0.01f

// ASTEROIDS
#define ASTEROID_INITIAL_SPEED 0.03f
#define ASTEROID_SPEED_INCREMENT 0.005f
#define ASTEROID_INITIAL_GEN_FREQUENCY 2000
#define ASTEROID_GEN_FREQUENCY_DECREMENT 100 

// TEXT
#define MAX_TEXT_LENGTH 20
#define TEXT_Z 0
#define TEXT_SIZE 0.005

// PSYCHEDELIC WELL
#define RANDOM_ITEM_NO 35
#define RANDOM_ITEM_MIN_SPEED -0.02
#define RANDOM_ITEM_MAX_SPEED 0.02
#define RANDOM_ITEM_MIN_ROT_SPEED -0.01
#define RANDOM_ITEM_MAX_ROT_SPEED 0.01

// ENDGAME
#define DARKEN_DECREMENT 0.01
#define DARKEN_TIMES 75